# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-04-15 03:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hosts', '0001_initial'),
        ('wagtailimages', '0016_deprecate_rendition_filter_relation'),
        ('experiences', '0001_initial'),
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostplacerelationship',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_host_relationship', to='places.PlacePage'),
        ),
        migrations.AddField(
            model_name='hostpage',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Host image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='hostinterestrelationship',
            name='host_interests',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest_host_relationship', to='hosts.HostInterest'),
        ),
        migrations.AddField(
            model_name='hostinterestrelationship',
            name='host_page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_interest_relationship', to='hosts.HostPage'),
        ),
        migrations.AddField(
            model_name='hostindexpage',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Hosts listing image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='hostexperiencerelationship',
            name='experiences',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_host_relationship', to='experiences.ExperiencePage'),
        ),
        migrations.AddField(
            model_name='hostexperiencerelationship',
            name='host_page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_experience_relationship', to='hosts.HostPage'),
        ),
    ]
