# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-04-27 03:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0002_auto_20170415_0410'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254, verbose_name='Language')),
            ],
            options={
                'verbose_name': 'Language',
                'ordering': ['title'],
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.CreateModel(
            name='HostLanguageRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_languages', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_host_relationship', to='hosts.HostLanguage')),
                ('host_page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_language_relationship', to='hosts.HostPage')),
            ],
        ),
        migrations.RemoveField(
            model_name='hostinterestrelationship',
            name='host_interests',
        ),
        migrations.RemoveField(
            model_name='hostinterestrelationship',
            name='host_page',
        ),
        migrations.DeleteModel(
            name='HostInterest',
        ),
        migrations.DeleteModel(
            name='HostInterestRelationship',
        ),
    ]
