# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-04-27 04:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('hosts', '0003_auto_20170427_0443'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_interests', to='hosts.HostPage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosts_hostinterest_items', to='taggit.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='hostpage',
            name='interests',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='hosts.HostInterest', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
