# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-05-09 03:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0003_auto_20170427_0443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostexperiencerelationship',
            name='experiences',
        ),
        migrations.RemoveField(
            model_name='hostexperiencerelationship',
            name='host_page',
        ),
        migrations.DeleteModel(
            name='HostExperienceRelationship',
        ),
    ]
