# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-05-11 03:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0004_auto_20170509_0449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostplacerelationship',
            name='host_page',
        ),
        migrations.RemoveField(
            model_name='hostplacerelationship',
            name='place',
        ),
        migrations.DeleteModel(
            name='HostPlaceRelationship',
        ),
    ]
