# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-04-29 02:54
from __future__ import unicode_literals

from django.db import migrations
import modelcluster.contrib.taggit


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0004_auto_20170427_0512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostpage',
            name='interests',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='Eg., "Korean Dramas"', through='hosts.HostInterest', to='taggit.Tag', verbose_name='Interests/Hobby'),
        ),
    ]
