# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-08-06 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0006_auto_20170615_0435'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostpage',
            name='email_address',
            field=models.EmailField(default='yan.pye.aung@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
