# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-03 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingslot',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes about the booking slot', null=True),
        ),
    ]
