# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-12 21:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_bookingslot_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingSlotRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(db_index=True)),
                ('first_name', models.CharField(max_length=254)),
                ('last_name', models.CharField(max_length=254)),
                ('email_address', models.EmailField(max_length=254)),
                ('group_size', models.PositiveIntegerField()),
                ('message', models.TextField(blank=True, help_text='Special notes', null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='experience_page',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='experiences.ExperiencePage', verbose_name='experience page'),
        ),
        migrations.AlterField(
            model_name='bookingslot',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_slots', related_query_name='booking_slot', to='bookings.Booking', verbose_name='Booking for Experience page'),
        ),
        migrations.AddField(
            model_name='bookingslotrequest',
            name='slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_slot_requests', related_query_name='booking_slot_request', to='bookings.BookingSlot', verbose_name='Request for booking slot'),
        ),
    ]
