# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-05-11 03:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
        ('experiences', '0003_experiencepage_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencepage',
            name='place',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.PROTECT, related_name='experiences', to='places.PlacePage'),
            preserve_default=False,
        ),
    ]
