# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-05-12 04:08
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0004_experiencepage_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencepage',
            name='host',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='providing_experiences', to='hosts.HostPage'),
        ),
    ]
